name: Package Remote Networking

on:
  push:
  workflow_dispatch:

jobs:
  package-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      run: |
        docker run -v "$(pwd):/src/" cdrx/pyinstaller-linux

    - uses: actions/upload-artifact@v2
      with:
        name: linux-remote-networking
        path: dist/linux/remote_networking

  package-windows:
    # The Windows builds actually happen on a docker image
    # with WINE, so it doesn't matter which OS we use.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      run: |
         docker run -v "$(pwd):/src/" cdrx/pyinstaller-windows

    - uses: actions/upload-artifact@v2
      with:
        name: windows-remote-networking.exe
        path: dist/windows/remote_networking.exe

  package-osx:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Package Application
      run: |
         pip install pyinstaller
         pip install -r requirements.txt
         pyinstaller -y remote_networking.spec

    - uses: actions/upload-artifact@v2
      with:
        name: mac-remote-networking
        path: dist/remote_networking
